# Generated by Django 3.2.9 on 2021-11-08 20:26
import logging

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations

GROUPS = ['System Operator', 'Experience Owner', 'Experience Manager',
          'Experience Facilitator', 'Experience Participant']
MODELS = ['course information mapping']
PERMISSIONS = ['view', 'add', 'change', 'delete']


def forwards_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Perm = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for custom in MODELS:
        ContentType.objects.get(
            app_label='xds_api',
            model=custom.replace(" ", "")
        ).delete()
        ct = ContentType.objects.filter(
            model=custom.replace(" ", "")
        )
        if ct.exists():
            ct.delete()

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_contenttypes(app_config, verbosity=0)
        app_config.models_module = None

    for group in GROUPS:
        new_group, created = Group.objects.get_or_create(name=group)

        for model in MODELS:
            for permission in PERMISSIONS:
                name = 'Can {} {}'.format(permission, model)
                print("Creating {}".format(name))

                model_comb = model
                value = model_comb.replace(" ", "")
                codename = '{}_{}'.format(permission, value)

                try:
                    content_type = \
                        ContentType.objects.get(model=value)
                    model_add_perm, created = \
                        Perm.objects.get_or_create(codename=codename,
                                                   name=name,
                                                   content_type=content_type)
                except Perm.DoesNotExist:
#                    logging.warning("Permission not found with name '{}'.".
#                                    format(name))
                    logging.warning("Permission not found with %s", name)
                    continue

                new_group.permissions.add(model_add_perm)

    print("Updated Course Information Mapping permissions.")


def reverse_func(apps, schema_editor):
    # reverse_func() should delete them.
    Group = apps.get_model('auth', 'Group')
    Perm = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    # get new content types and permissions and delete them
    for custom in MODELS:
        content_type = ContentType.objects.get(
            model=custom.replace(" ", "")
        )
        Perm.objects.filter(content_type=content_type).delete()
        content_type.delete()

    # recreate the old content types and permissions
    for custom in MODELS:
        ContentType.objects.get_or_create(
            app_label='core',
            model=custom.replace(" ", "")
        )

    for group in GROUPS:
        new_group, created = Group.objects.get_or_create(name=group)

        for model in MODELS:
            for permission in PERMISSIONS:
                name = 'Can {} {}'.format(permission, model)
                print("Creating {}".format(name))

                model_comb = model
                value = model_comb.replace(" ", "")
                codename = '{}_{}'.format(permission, value)

                try:
                    content_type = \
                        ContentType.objects.get(model=value)
                    model_add_perm, created = \
                        Perm.objects.get_or_create(codename=codename,
                                                   name=name,
                                                   content_type=content_type)
                except Perm.DoesNotExist:
#                    logging.warning("Permission not found with name '{}'.".
#                                    format(name))
                    logging.warning("Permission not found with %s", name)
                    continue

                new_group.permissions.add(model_add_perm)


class Migration(migrations.Migration):
    dependencies = [
        ('xds_api', '0003_move_permissions'),
        ('users', '0001_initial'),
        ('configurations', '0002_courseinformationmapping'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
