# Generated by Django 3.2.11 on 2022-01-07 16:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('xds_api', '0001_initial'),
    ]

    run_before = [
    ]


    operations = [
        migrations.CreateModel(
            name='XDSConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('target_xis_metadata_api', models.CharField(default='http://localhost:8080/api/metadata/', help_text='Enter the XIS api endpoint to query metadata', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XDSUIConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('search_results_per_page', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, 'results per page should be at least 1')])),
                ('course_img_fallback', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('xds_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configurations.xdsconfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
