# Generated by Django 3.2.11 on 2022-01-28 18:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('core', '0006_delete_courseinformationmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInformationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_title', models.CharField(help_text='Enter the title of the coursefound in the elasticsearch', max_length=200)),
                ('course_description', models.CharField(help_text='Enter the description of the course found in the elasticsearch', max_length=200)),
                ('course_url', models.CharField(help_text='Enter the url of the course found in the elasticsearch', max_length=200)),
                ('xds_ui_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_information', to='configurations.xdsuiconfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
