# Generated by Django 3.2.12 on 2022-03-07 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configurations', '0003_xseconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='xdsconfiguration',
            name='default_user_group',
            field=models.ForeignKey(help_text='Select the group to assign new users to', blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
