# Generated by Django 3.2.20 on 2023-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_auto_20220721_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformationmapping',
            name='course_derived_from',
            field=models.CharField(default='P2881_Core.DerivedFrom', help_text='Enter the mapping for the reference to the course derived from found in the elasticsearch', max_length=200),
        ),
    ]
