# Generated by Django 4.2.14 on 2024-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_courseinformationmapping_course_derived_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformationmapping',
            name='course_competency',
            field=models.CharField(default='Course.CourseLearningOutcome', help_text='Enter the mapping for the reference to the competency taught', max_length=200),
        ),
    ]
