# Generated by Django 4.2.16 on 2024-10-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_courseinformationmapping_course_derived_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformationmapping',
            name='course_time',
            field=models.CharField(default='Course.EstimatedCompletionTime', help_text='Enter the mapping for the estimated completion time  for the course found in the elasticsearch', max_length=200),
        ),
        migrations.AddField(
            model_name='courseinformationmapping',
            name='course_type',
            field=models.CharField(default='Course.CourseType', help_text='Enter the mapping for the Course type of the course found in the elasticsearch', max_length=200),
        ),
    ]
