# Generated by Django 4.2.16 on 2024-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_courseinformationmapping_course_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='xdsuiconfiguration',
            name='ui_logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
