# Generated by Django 4.2.16 on 2024-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_xdsuiconfiguration_ui_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xdsuiconfiguration',
            name='ui_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
