# Generated by Django 4.2.16 on 2024-10-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_courseinformationmapping_course_time_and_more'),
        ('configurations', '0009_alter_xdsuiconfiguration_ui_logo'),
    ]

    operations = [
    ]
