# Generated by Django 4.2.16 on 2024-11-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_merge_20241026_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformationmapping',
            name='course_derived_from',
            field=models.CharField(default='P2881-Core.DerivedFrom', help_text='Enter the mapping for the reference to the course derived from found in the elasticsearch', max_length=200),
        ),
    ]
