# Generated by Django 4.2.16 on 2024-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0011_alter_courseinformationmapping_course_derived_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformationmapping',
            name='course_subject',
            field=models.CharField(default='p2881-core.Subject', help_text='Enter the mapping for the course subject', max_length=200),
        ),
    ]
