# Generated by Django 4.2.18 on 2025-01-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0012_courseinformationmapping_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='xdsconfiguration',
            name='lrs_endpoint',
            field=models.CharField(blank=True, help_text='Enter the xAPI LRS Endpoint to send data to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='xdsconfiguration',
            name='lrs_password',
            field=models.CharField(blank=True, help_text='Enter the xAPI LRS HTTP Basic Auth password', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='xdsconfiguration',
            name='lrs_username',
            field=models.CharField(blank=True, help_text='Enter the xAPI LRS HTTP Basic Auth username', max_length=200, null=True),
        ),
    ]
