# Generated by Django 3.2.9 on 2021-11-05 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_savedfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xdsuser',
            options={},
        ),
        migrations.AlterField(
            model_name='xdsuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
