# Generated by Django 3.2.11 on 2022-01-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211105_0538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XDSUser',
        ),
    ]
