# Generated by Django 3.2.11 on 2022-01-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('core', '0004_delete_xdsuser'),
    ]

    run_before = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='xdsuiconfiguration',
            name='xds_configuration',
        ),
        migrations.AlterField(
            model_name='coursedetailhighlight',
            name='xds_ui_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_highlights', to='configurations.xdsuiconfiguration'),
        ),
        migrations.AlterField(
            model_name='courseinformationmapping',
            name='xds_ui_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_information', to='configurations.xdsuiconfiguration'),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='xds_ui_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.xdsuiconfiguration'),
        ),
        migrations.AlterField(
            model_name='searchsortoption',
            name='xds_ui_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_sort_options', to='configurations.xdsuiconfiguration'),
        ),
        migrations.DeleteModel(
            name='XDSConfiguration',
        ),
        migrations.DeleteModel(
            name='XDSUIConfiguration',
        ),
    ]
