# Generated by Django 3.2.11 on 2022-01-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220107_1605'),
        ('xds_api', '0003_move_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseInformationMapping',
        ),
    ]
