# Generated by Django 3.2.12 on 2022-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_courseinformationmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestlist',
            name='public',
            field=models.BooleanField(default=False, help_text='Make list searchable to other users'),
        ),
        migrations.AlterField(
            model_name='interestlist',
            name='description',
            field=models.TextField(help_text='Enter a description for the list'),
        ),
    ]
