# Generated by Django 3.2.14 on 2022-07-21 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220309_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailhighlight',
            name='rank',
            field=models.IntegerField(default=1, help_text='Order in which highlight show on the course detail page (2 items per row)', validators=[django.core.validators.MinValueValidator(1, 'rank should be at least 1')]),
        ),
    ]
